config/routes.rb
Rails.application.routes.draw do
  

  #get 'resource/new'

  #get 'resource/summary'

  get 'sections/new'

  root                           'splash#index'

  post   'login'      =>    'sessions#create'
  delete 'logout'     =>    'sessions#destroy'
  get    'login'      =>    'sessions#new'
  post   'login'      =>    'sessions#create'


  get      'premio'     =>       'splash#premio'
  get      'convocatoria'     =>       'splash#convocatoria'
  get      'ganadores'  =>       'splash#ganadores'
  get      'registro'   =>       'splash#registro' 

  get      'admin-cummins' =>   'proyects#index'

  #get     'acciones'        =>    'proposals#actions'
  #get     'actividades'     =>    'proposals#activities'
  #get     'metodologias'    =>    'proposals#methodologies'
  #get     'impactos'        =>    'proposals#impacts'
  #get     'recursos'        =>    'proposals#resources'

  # get      'justificacion'    =>    'proyects#justificacion'
  # patch    'justificacion'    =>    'proyects#justificacion_update'
  # put      'justificacion'    =>    'proyects#justificacion_update'


  resources :recipients
  resources :sections
  
  resources :account_activations, only: [:edit]
  resources :users#, only: [:new, :create]
  resources :proyects do 
    member do 
      get :justificacion
      patch :justificacion_update

      get :petition
      patch :petition_update

      get :gobjectives
      patch :gobjectives_update

      get :eobjectives
      patch :eobjectives_update

      get :beneficiarios
      patch :beneficiarios_update

      get :investment
      patch :investment_update

      get :continuity
      patch :continuity_update

      get :close_proyect

      get :review

      get :success
    end
  end

  resources :proposals do
    member do
      get :actions
      patch :actions_update

      get :activities
      patch :activities_update

      get :impacts
      patch :impacts_update

      get :methodologies
      patch :methodologies_update

      get :resources
      patch :resources_update
    end
  end

  resources :resource do
    member do

      get :summary
    end
  end

end

app/models/proyect.rb
# == Schema Information
#
# Table name: proyects
#
#  id                          :integer          not null, primary key
#  user_id                     :integer          not null
#  logo_updated_at             :datetime
#  logo_content_type           :string(255)
#  logo_file_size              :integer
#  logo_file_name              :string(255)
#  topic                       :integer          default(0)
#  mission_vision              :string(500)
#  yr_operation                :string(255)
#  programs_offered            :string(255)
#  achievements                :string(500)
#  beneficiarios               :integer
#  comments                    :string(500)
#  step                        :integer          default(0)
#  existent_new                :integer          default(0)
#  idea_emerge                 :integer
#  idea_emerge_exp             :string(255)
#  procedure_taken             :integer
#  importance                  :string(255)
#  improvement_importance_a    :string(255)      default("")
#  improvement_importance_b    :string(255)      default("")
#  improvement_importance_c    :string(255)      default("")
#  improvement_importance_d    :string(255)      default("")
#  improvement_importance_e    :string(255)      default("")
#  improvement_importance_f    :string(255)      default("")
#  col_211_a                   :string(255)
#  col_211_b                   :string(255)
#  col_211_c                   :string(255)
#  col_211_d                   :string(255)
#  col_211_e                   :string(255)
#  col_212_a                   :string(255)
#  col_212_b                   :string(255)
#  col_212_c                   :string(255)
#  col_212_d                   :string(255)
#  col_212_e                   :string(255)
#  col_212_f                   :string(255)
#  col_oe1                     :string(255)
#  col_oe1_a                   :string(255)
#  col_oe1_b                   :string(255)
#  col_oe1_c                   :string(255)
#  col_oe1_d                   :string(255)
#  col_oe1_e                   :string(255)
#  col_oe2                     :string(255)
#  col_oe2_a                   :string(255)
#  col_oe2_b                   :string(255)
#  col_oe2_c                   :string(255)
#  col_oe2_d                   :string(255)
#  col_oe2_e                   :string(255)
#  col_oe3                     :string(255)
#  col_oe3_a                   :string(255)
#  col_oe3_b                   :string(255)
#  col_oe3_c                   :string(255)
#  col_oe3_d                   :string(255)
#  col_oe3_e                   :string(255)
#  ben_group                   :integer
#  ben_age_range               :integer          default(0)
#  ben_age_range2              :integer          default(0)
#  ben_risk                    :integer
#  ben_risk_exp                :string(255)
#  ben_number                  :integer          default(1)
#  ben_part_regular            :integer          default(0)
#  ben_part_eventual           :integer          default(0)
#  investment_a                :string(15)
#  investment_b                :string(15)
#  investment_c                :string(15)
#  investment_d                :string(15)
#  investment_e                :string(15)
#  investment_f                :string(255)
#  investment_sum              :string(15)
#  total_weeks                 :integer          default(0)
#  col_continuity_action1      :string(255)
#  col_continuity_indicator1   :string(255)
#  col_continuity_responsible1 :string(255)
#  col_continuity_action2      :string(255)
#  col_continuity_indicator2   :string(255)
#  col_continuity_responsible2 :string(255)
#  col_continuity_action3      :string(255)
#  col_continuity_indicator3   :string(255)
#  col_continuity_responsible3 :string(255)
#  updated_at                  :datetime         not null
#  created_at                  :datetime         not null
#  name                        :string(255)
#  importance_text             :string(255)      default("")
#  benef_regular               :integer
#  benef_eventual              :integer
#  importance_text_b           :string(255)      default("")
#  importance_text_c           :string(255)      default("")
#  importance_text_d           :string(255)      default("")
#  importance_text_e           :string(255)      default("")
#  importance_text_f           :string(255)      default("")
#  importance_text_g           :string(255)      default("")
#  importance_text_h           :string(255)      default("")
#  status                      :integer          default(0)
#

class Proyect < ActiveRecord::Base
  belongs_to :user
  has_many :recipients

  has_attached_file :logo
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  validates :programs_offered, length: {maximum: 255}


  validates :idea_emerge_exp, length: {maximum: 255}
  validates :importance, length: {maximum: 255}
  validates :improvement_importance_a, length: {maximum: 255}
  validates :improvement_importance_b, length: {maximum: 255}
  validates :improvement_importance_c, length: {maximum: 255}
  validates :improvement_importance_d, length: {maximum: 255}
  validates :improvement_importance_e, length: {maximum: 255}
  validates :improvement_importance_f, length: {maximum: 255}
  validates :col_211_a, length: {maximum: 255}
  validates :col_211_b, length: {maximum: 255}
  validates :col_211_c, length: {maximum: 255}
  validates :col_211_d, length: {maximum: 255}
  validates :col_211_e, length: {maximum: 255}
  validates :col_212_a, length: {maximum: 255}
  validates :col_212_b, length: {maximum: 255}
  validates :col_212_c, length: {maximum: 255}
  validates :col_212_d, length: {maximum: 255}
  validates :col_212_e, length: {maximum: 255}
  validates :col_212_f, length: {maximum: 255}
  validates :col_oe1, length: {maximum: 255}
  validates :col_oe1_a, length: {maximum: 255}
  validates :col_oe1_b, length: {maximum: 255}
  validates :col_oe1_c, length: {maximum: 255}
  validates :col_oe1_d, length: {maximum: 255}
  validates :col_oe1_e, length: {maximum: 255}
  validates :col_oe2, length: {maximum: 255}
  validates :col_oe2_a, length: {maximum: 255}
  validates :col_oe2_b, length: {maximum: 255}
  validates :col_oe2_c, length: {maximum: 255}
  validates :col_oe2_d, length: {maximum: 255}
  validates :col_oe2_e, length: {maximum: 255}
  validates :col_oe3, length: {maximum: 255}
  validates :col_oe3_a, length: {maximum: 255}
  validates :col_oe3_b, length: {maximum: 255}
  validates :col_oe3_c, length: {maximum: 255}
  validates :col_oe3_d, length: {maximum: 255}
  validates :col_oe3_e, length: {maximum: 255}
  validates :ben_risk_exp, length: {maximum: 255}
  validates :investment_a, length: {maximum: 15}
  validates :investment_b, length: {maximum: 15}
  validates :investment_c, length: {maximum: 15}
  validates :investment_d, length: {maximum: 15}
  validates :investment_e, length: {maximum: 15}
  validates :investment_f, length: {maximum: 255}
  validates :investment_sum, length: {maximum: 15}
  validates :col_continuity_action1, length: {maximum: 255}
  validates :col_continuity_indicator1, length: {maximum: 255}
  validates :col_continuity_responsible1, length: {maximum: 255}
  validates :col_continuity_action2, length: {maximum: 255}
  validates :col_continuity_indicator2, length: {maximum: 255}
  validates :col_continuity_responsible2, length: {maximum: 255}
  validates :col_continuity_action3, length: {maximum: 255}
  validates :col_continuity_indicator3, length: {maximum: 255}
  validates :col_continuity_responsible3, length: {maximum: 255}
  validates :importance_text_b, length: {maximum: 255}
  validates :importance_text_c, length: {maximum: 255}
  validates :importance_text_d, length: {maximum: 255}
  validates :importance_text_e, length: {maximum: 255}
  validates :importance_text_f, length: {maximum: 255}
  validates :importance_text_g, length: {maximum: 255}
  validates :importance_text_h, length: {maximum: 255}

  SELECT_TOPIC = {
    'Educacion' => 0,
    'Justicia Social' => 1,
    'Medio Ambiente' => 2
  }

  READ_TOPIC = {
    0 => 'Educacion',
    1 => 'Justicia Social',
    2 => 'Medio Ambiente'
  }

  READ_EXISTENT_NEW = {
    0 => 'Petición para mejorar un programa o proyecto ya existente',
    1 => 'Proyecto o programa nuevo'
  }

  READ_IDEA_EMERGE = {
    0 => 'De la comunidad o beneficiarios',
    1 => 'De la OSC',
    2 => 'Otro'
  }

  READ_PROCEDURE_TAKEN = {
    0 => 'Se observó', 
    1 => 'Un estudio', 
    2 => 'Un testimonio'
  }


  SELECT_BENEF_RISK = {
    'Discapacidad'  => 0,
    'Violencia' => 1,
    'Enfermedad' => 2,
    'Abandono' => 3,
    'Marginacion' => 4,
    'Desnutricion' => 5,
    'Otro' => 6
  }

  READ_BENEF_RISK = {
    0 => 'Discapacidad',
    1 => 'Violencia',
    2 => 'Enfermedad',
    3 => 'Abandono',
    4 => 'Marginacion',
    5 => 'Desnutricion',
    6 => 'Otro'
  }

  SELECT_BENEF_GROUP = {
    'Hombres' => 0,
    'Mujeres'  => 1,
    "Ambos"  => 2
  }

  READ_BENEF_GROUP = {
    0 => 'Hombres',
    1 => "Mujeres",
    2 => "Ambos"
  }

  READ_IMPORTANCE = {
    0 => 'Ampliar el número de programas o servicios',
    1 => 'Le doy continuidad a un proyecto anterior',
    2 => 'Mejora la calidad de atención',
    3 => 'Contribuyo a la solución de un problema nuevo en mis beneficiarios',
    4 => 'Mejoro mi operación interna',
    5 => 'Genero un ahorro a mis gastos',
    6 => 'Genero un ingreso nuevo ',
    7 => 'Otro'
  }

  SELECT_IMPORTANCE = {
    'Ampliar el número de programas o servicios' => 0,
    'Le doy continuidad a un proyecto anterior ¿Cuál?' => 1,
    'Mejora la calidad de atención ¿cómo?' => 2,
    'Contribuyo a la solución de un problema nuevo en mis beneficiarios ¿cómo?' => 3,
    'Mejoro mi operación interna ¿cómo?' => 4,
    'Genero un ahorro a mis gastos ¿cómo, mediante qué acciones y metodología?' => 5,

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :logged_in_user,   except: [:show]
  before_action :correct_user,   except: [:show, :index]
  before_action :editable, except: [:show, :index, :review]
  # before_action :require_admin_session, only: [:index, :show]

  def index
    @proyects = Proyect.all
  end
    
  def show
    @proyect = Proyect.find(params[:id])
  end

  def edit
  end  

  def update
    if @proyect.update_attributes(proyect_params)
      if @proyect.is_new?
        redirect_to :back #justificacion_proyect_path(@proyect)
      else
        redirect_to :back # petition_proyect_path(@proyect)  
      end
    else
      render 'edit'
    end
  end

  def justificacion
  end

  def justificacion_update
    if @proyect.update_attributes(justification_params)
      redirect_to :back #gobjectives_proyect_path(@proyect)
    else
      render 'justificacion'
    end    
  end

  def petition
  end

  def petition_update
    if @proyect.update_attributes(petition_params)
      redirect_to :back #gobjectives_proyect_path(@proyect)
    else
      render 'petition'
    end    
  end

  def gobjectives
  end

  def gobjectives_update
    if @proyect.update_attributes(gobjectives_params)
      redirect_to :back #eobjectives_proyect_path(@proyect)
    else
      render 'gobjectives'
    end
  end

  def eobjectives
  end

  def eobjectives_update
    if @proyect.update_attributes(eobjectives_params)
      redirect_to :back #new_recipient_path # beneficiarios_proyect_path(@proyect)
    else
      render 'gobjectives'
    end
  end

  def beneficiarios_update
    if @proyect.update_attributes(beneficiarios_params)
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def investment
  end

  def investment_update
    if @proyect.update_attributes(investment_params)
      redirect_to :back #continuity_proyect_path(@proyect)
    else
      render 'investment'
    end    
  end

  def continuity
  end

  def continuity_update
    if @proyect.update_attributes(continuity_params)
      redirect_to :back # success_proyect_path(@proyect)
    else
      render 'continuity'
    end
  end

  def success
  end

  def review
  end

  def close_proyect
    @proyect.close
    flash[:success] = "¡Proyecto enviado con éxito!"
    redirect_to :back
    
  end


  private
    def correct_user
      @proyect = Proyect.find(params[:id])
      # user this
      if current_user.proyect != @proyect
        redirect_to edit_proyect_path(current_user.proyect)
      end
    end

    def proyect_params
      params.require(:proyect).permit(:name, :topic, :existent_new)
    end

    def justification_params
      params.require(:proyect).permit(:idea_emerge, :idea_emerge_exp, :procedure_taken, :importance, :importance_text, :importance_text_b,:importance_text_c,:importance_text_d,:importance_text_e,:importance_text_f,:importance_text_g,:importance_text_h)
    end

    def petition_params
      params.require(:proyect).permit(:improvement_importance_a, :improvement_importance_b, :improvement_importance_c, :improvement_importance_d, :improvement_importance_e, :improvement_importance_f)
    end

    def gobjectives_params
      params.require(:proyect).permit(:col_211_a, :col_211_b, :col_211_c, :col_211_d, :col_211_e, :col_212_a, :col_212_b, :col_212_c, :col_212_d, :col_212_e, :col_212_f)
    end

    def eobjectives_params
      params.require(:proyect).permit(:col_oe1, :col_oe1_a, :col_oe1_b, :col_oe1_c, :col_oe1_d, :col_oe1_e, :col_oe2, :col_oe2_a, :col_oe2_b, :col_oe2_c, :col_oe2_d, :col_oe2_e, :col_oe3, :col_oe3_a, :col_oe3_b, :col_oe3_c, :col_oe3_d, :col_oe3_e)
    end

    def beneficiarios_params
      params.require(:proyect).permit(:ben_part_regular, :ben_part_eventual)
    end

    def investment_params
      params.require(:proyect).permit(:investment_a, :investment_b, :investment_c, :investment_d, :investment_e, :investment_f, :investment_sum, :total_weeks)
    end

    def continuity_params
      params.require(:proyect).permit(:col_continuity_action1, :col_continuity_indicator1, :col_continuity_responsible1, :col_continuity_action2, :col_continuity_indicator2, :col_continuity_responsible2, :col_continuity_action3, :col_continuity_indicator3, :col_continuity_responsible3)
    end

    def editable
      unless @proyect.editable?
        flash[:danger] = "El proyecto ha sido enviado. No se puede editar."
        redirect_to review_proyect_path(@proyect)
      end
    end
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/proyects/beneficiarios.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h2>3.1 Beneficiarios y Comunidades atendidas</h2>
      <hr>
      <%= form_for(@proyect, url: beneficiarios_update_proyect_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label :ben_group, "Grupo de beneficiarios" %>
        <%= f.select :ben_group, options_for_select(Proyect::SELECT_BENEF_GROUP.map {|opt| opt}, @proyect.ben_group), {include_blank: false}, {class: "form-control"}, required: true %>
        <br>

        <div class="row">
          <div class="col-md-6 pull-left">
            <%= f.label :ben_age_range, "Rango de edad (Desde)" %>
            <%= f.select :ben_age_range, options_for_select((1..100).step(1).to_a.map {|s| ["#{s}", s]}, @proyect.ben_age_range), {include_blank: false}, {class: "form-control"} %>
          </div>
          <div class="col-md-6">
            <%= f.label :ben_age_range2, "Rango de edad (Hasta)" %>
            <%= f.select :ben_age_range2, options_for_select((1..100).step(1).to_a.map {|s| ["#{s}", s]}, @proyect.ben_age_range2), {include_blank: false}, {class: "form-control"} %>
          </div>
        </div>
        <br>
          

        <div class="row">
          <div class="col-md-6 pull-left">
            <%= f.label :ben_risk, "Situación de riesgo / enfermedad" %>
            <%= f.select :ben_risk, options_for_select(Proyect::SELECT_BENEF_RISK.map {|opt| opt}, @proyect.ben_risk), {include_blank: false}, {class: "form-control"} %>
          </div>
          <div class="col-md-6">
            <%= f.label :ben_risk_exp, "¿Cuál? (en caso de seleccionar Otra)" %>
            <%= f.text_field :ben_risk_exp, class: 'form-control' %>
           </div>
        </div>
        <br>

        <%= f.label :ben_number, "¿Cuántos beneficiarios?" %>
        <%= f.number_field :ben_number, class: 'form-control' %>
        <br>

        <%= link_to "Atrás", eobjectives_proyect_path(@proyect), class: "btn btn-default" %>
        <%= f.submit "Siguiente", class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/proyects/continuity.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h2>5- Continuidad del Proyecto</h2>
      <h4>
        Mediante qué acciones vas a asegurar que tu programa o proyecto continuará  una vez que se termine este apoyo (Máximo 3)
      </h4>
      <hr>
      <%= form_for(@proyect, url: continuity_update_proyect_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="row">
          <div class="col-md-4">
            <%= f.label :col_continuity_action1, "Acción" %>
            <%= f.text_area :col_continuity_action1, class: 'form-control', required: true %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_indicator1, "Indicador" %>
            <%= f.text_area :col_continuity_indicator1, class: 'form-control', required: true %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_responsible1, "Responsable" %>
            <%= f.text_area :col_continuity_responsible1, class: 'form-control', required: true %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-4">
            <%= f.label :col_continuity_action2, "Acción" %>
            <%= f.text_area :col_continuity_action2, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_indicator2, "Indicador" %>
            <%= f.text_area :col_continuity_indicator2, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_responsible2, "Responsable" %>
            <%= f.text_area :col_continuity_responsible2, class: 'form-control' %>
          </div>
        </div>
        <br>

        <div class="row">
          <div class="col-md-4">
            <%= f.label :col_continuity_action3, "Acción" %>
            <%= f.text_area :col_continuity_action3, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_indicator3, "Indicador" %>
            <%= f.text_area :col_continuity_indicator3, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_responsible3, "Responsable" %>
            <%= f.text_area :col_continuity_responsible3, class: 'form-control' %>
          </div>
        </div>

        <br>
        <%= link_to "Atrás", investment_proyect_path(@proyect), class: "btn btn-default" %>
        <div class="pull-right">
          <%= f.submit "Guardar", class: "btn btn-primary" %>
          <%= link_to "Resumen", review_proyect_path(@proyect), class: "btn btn-default" %>
          
        </div>
      <% end %>  
    </div>
  </div>
</div>

app/views/proyects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-12 col-md-offset-3">
    
      <h1 class="text-center">Información General</h1>
      <hr>
      <%= form_for(@proyect) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <p>
          Nombre del Proyecto
        </p>
        <%= f.text_field :name, class: 'form-control', required: true %>
        <br>
        <p>
          Temática a participar
        </p>
        
        <%= f.radio_button :topic, '0' %> 
        <%= label :topic, 'Educacion' %>

        <%= f.radio_button :topic, '1' %>
        <%= label :topic, 'Justicia Social' %>

        <%= f.radio_button :topic, '2' %>
        <%= label :topic, 'Medio Ambiente' %>

        <br>
        <br>
        <br>
        <p>
            ¿Es una petición para mejorar un programa ya existente o es un proyecto o programa nuevo?
        </p>


        <%= f.radio_button :existent_new, '0' %>
        <%= label :topic, 'Petición para mejorar un programa o proyecto ya existente' %>
        <br>

        <%= f.radio_button :existent_new, '1' %>
        <%= label :topic, 'Proyecto o programa nuevo' %>

        <br>
        <%#= f.collection_radio_buttons :topic, options_for_select(Proyect::SELECT_TOPIC.map {|opt| opt}, @proyect.topic), {include_blank: false}, {class: "form-control"} %>
        <br>
        <br>
        <% if @proyect.logo.exists? %>
            <%= image_tag(@proyect.logo.url, width: "300px") %> 
        <% end %>
        <div class="pull-right">
            
            <%= f.submit "Guardar", class: "btn btn-primary" %>


            <% if @proyect.is_new? %>
                <%= link_to "Siguiente", justificacion_proyect_path(@proyect), class: "btn btn-default" %>
            <% else %>
                <%= link_to "Siguiente", petition_proyect_path(@proyect), class: "btn btn-default" %>

            <% end %>
        </div>

        
      <% end %>
    </div>
  </div>
</div>

app/views/proyects/eobjectives.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h3>
        2.2 Objetivo específico:
      </h3>
      <h4>
        ¿Qué distintas actividades vas a poner en práctica para lograr tu objetivo General? <br>
        (Mínimo 1 - Máximo 3 Objetivos)
      </h4>
      <hr>
      <%= form_for(@proyect, url: eobjectives_update_proyect_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%#= f.label :col_oe1, "Objetivo Específico 1" %>
        <%#= f.text_field :col_oe1, class: 'form-control', required: true %>
        <p>Objetivo Específico 1</p>
        <%= f.label :col_oe1_a, "Actividad secundaria o derivada en ar, er, ir" %>
        <%= f.text_field :col_oe1_a, class: 'form-control', required: true %>
        <%= f.label :col_oe1_b, "¿Cuál es el principal beneficio que vas a lograr?" %>
        <%= f.text_field :col_oe1_b, class: 'form-control', required: true %>
        <%= f.label :col_oe1_c, "¿Para quienes? Mujeres, niños, edad, discapacitados" %>
        <%= f.text_field :col_oe1_c, class: 'form-control', required: true %>
        <%= f.label :col_oe1_d, "¿En dónde? Municipio, colonia" %>
        <%= f.text_field :col_oe1_d, class: 'form-control', required: true %>
        <%= f.label :col_oe1_e, "¿Cómo? A través de capacitación, consultas, equipar, etc." %>
        <%= f.text_field :col_oe1_e, class: 'form-control', required: true %>
        <br>

        <%#= f.label :col_oe2, "Objetivo Específico 2" %>
        <%#= f.text_field :col_oe2, class: 'form-control' %>
        <p>Objetivo Específico 2</p>
        <%= f.label :col_oe2_a, "Actividad secundaria o derivada en ar, er, ir" %>
        <%= f.text_field :col_oe2_a, class: 'form-control' %>
        <%= f.label :col_oe2_b, "¿Cuál es el principal beneficio que vas a lograr?" %>
        <%= f.text_field :col_oe2_b, class: 'form-control' %>
        <%= f.label :col_oe2_c, "¿Para quienes? Mujeres, niños, edad, discapacitados" %>
        <%= f.text_field :col_oe2_c, class: 'form-control' %>
        <%= f.label :col_oe2_d, "¿En dónde? Municipio, colonia" %>
        <%= f.text_field :col_oe2_d, class: 'form-control' %>
        <%= f.label :col_oe2_e, "¿Cómo? A través de capacitación, consultas, equipar, etc." %>
        <%= f.text_field :col_oe2_e, class: 'form-control' %>
        <br>

        <%#= f.label :col_oe3, "Objetivo Específico 3" %>
        <%#= f.text_field :col_oe3, class: 'form-control' %>
        <p>Objetivo Específico 3</p>
        <%= f.label :col_oe3_a, "Actividad secundaria o derivada en ar, er, ir" %>
        <%= f.text_field :col_oe3_a, class: 'form-control' %>
        <%= f.label :col_oe3_b, "¿Cuál es el principal beneficio que vas a lograr?" %>
        <%= f.text_field :col_oe3_b, class: 'form-control' %>
        <%= f.label :col_oe3_c, "¿Para quienes? Mujeres, niños, edad, discapacitados" %>
        <%= f.text_field :col_oe3_c, class: 'form-control' %>
        <%= f.label :col_oe3_d, "¿En dónde? Municipio, colonia" %>
        <%= f.text_field :col_oe3_d, class: 'form-control' %>
        <%= f.label :col_oe3_e, "¿Cómo? A través de capacitación, consultas, equipar, etc." %>
        <%= f.text_field :col_oe3_e, class: 'form-control' %>
        <br>

        <%= link_to "Atrás", gobjectives_proyect_path(@proyect), class: "btn btn-default" %>
        <div class="pull-right">
            <%= f.submit "Guardar", class: "btn btn-primary" %>
            <%= link_to "Siguiente", new_recipient_path, class: "btn btn-default" %>
            
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<br>

app/views/proyects/index.html.erb
<div class="container">
  <br>
  <br>
  <table class="table" id="index_table">
    <thead>
      <tr>
        <th>Nombre AC</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @proyects.each do |proyect| %>
        <tr class="fas" data-link="<%= proyect_path(proyect) %>">
          <td><%= proyect.user.ac_name %></td>
          <td><%= proyect.user.email %></td>
          <td class="text-center"><%= link_to "Ver Detalles", proyect_path(proyect), class: "btn btn-sm btn-default" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>